version: '3.8'

services:
  app:
    build: .
    container_name: testapp-dev
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - DB_PATH=/app/data/app.db
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - COOKIE_SECRET=${COOKIE_SECRET}
    volumes:
      - app_data_dev:/app/data

volumes:
  app_data_dev:
